In [10]:
import numpy as np

# Número de contêineres e slots
n_conteiners = 30
m_slots = 30  # número de slots disponíveis

# Função para gerar um cromossomo inicial
def gerar_cromossomo(n, m):
    conteiners = np.arange(n)
    np.random.shuffle(conteiners)  # Embaralha a lista de contêineres
    slots = np.random.choice(np.arange(m), n, replace=False)  # Seleciona slots únicos aleatoriamente
    return np.vstack((conteiners, slots))

# Gerando uma população inicial de cromossomos
def gerar_populacao_inicial(tam_pop, n, m):
    populacao = [gerar_cromossomo(n, m) for _ in range(tam_pop)]
    return populacao

# Função de avaliação (fitness)
def avaliar_cromossomo(cromossomo):
    # Exemplo de função de avaliação que considera a soma dos índices dos slots
    fitness = np.sum(cromossomo[1])
    return fitness

# Seleção por torneio
def selecao_torneio(populacao, fitness, k=3):
    selecionados = []
    for _ in range(len(populacao)):
        competidores = np.random.choice(len(populacao), k, replace=False)
        melhor = min(competidores, key=lambda x: fitness[x])
        selecionados.append(populacao[melhor])
    return selecionados

# Operador de cruzamento
def cruzamento(pai1, pai2):
    ponto = np.random.randint(1, len(pai1[0]))
    filho1 = np.hstack((pai1[:, :ponto], pai2[:, ponto:]))
    filho2 = np.hstack((pai2[:, :ponto], pai1[:, ponto:]))
    
    # Garantir que os slots não se repitam
    filho1 = corrigir_repeticao(filho1)
    filho2 = corrigir_repeticao(filho2)
    
    return filho1, filho2

def corrigir_repeticao(cromossomo):
    # Identificar slots repetidos e corrigir
    slots_unicos, indices = np.unique(cromossomo[1], return_index=True)
    todos_slots = np.arange(m_slots)
    slots_faltantes = np.setdiff1d(todos_slots, slots_unicos)
    
    for i in range(len(cromossomo[1])):
        if i not in indices:
            cromossomo[1, i] = slots_faltantes[0]
            slots_faltantes = np.delete(slots_faltantes, 0)
    
    # Garantir que os contêineres não se repitam
    conteiners_unicos, indices = np.unique(cromossomo[0], return_index=True)
    todos_conteiners = np.arange(n_conteiners)
    conteiners_faltantes = np.setdiff1d(todos_conteiners, conteiners_unicos)
    
    for i in range(len(cromossomo[0])):
        if i not in indices:
            cromossomo[0, i] = conteiners_faltantes[0]
            conteiners_faltantes = np.delete(conteiners_faltantes, 0)
    
    return cromossomo

# Operador de mutação
def mutacao(cromossomo, taxa_mutacao=0.01):
    if np.random.rand() < taxa_mutacao:
        idx1, idx2 = np.random.choice(len(cromossomo[0]), 2, replace=False)
        cromossomo[1, idx1], cromossomo[1, idx2] = cromossomo[1, idx2], cromossomo[1, idx1]
    return cromossomo

# Função principal do Algoritmo Genético
def algoritmo_genetico(tam_pop, n, m, geracoes, taxa_mutacao, k_torneio):
    populacao = gerar_populacao_inicial(tam_pop, n, m)
    melhor_solucao = None
    melhor_fitness = np.inf
    
    for geracao in range(geracoes):
        fitness = [avaliar_cromossomo(cromossomo) for cromossomo in populacao]
        
        nova_populacao = selecao_torneio(populacao, fitness, k_torneio)
        
        filhos = []
        for i in range(0, len(nova_populacao), 2):
            pai1, pai2 = nova_populacao[i], nova_populacao[i+1]
            filho1, filho2 = cruzamento(pai1, pai2)
            filhos.append(mutacao(filho1, taxa_mutacao))
            filhos.append(mutacao(filho2, taxa_mutacao))
        
        populacao = filhos
        
        # Avaliação do melhor cromossomo da geração atual
        fitness = [avaliar_cromossomo(cromossomo) for cromossomo in populacao]
        melhor_idx = np.argmin(fitness)
        if fitness[melhor_idx] < melhor_fitness:
            melhor_fitness = fitness[melhor_idx]
            melhor_solucao = populacao[melhor_idx]
        
        print(f"Geração {geracao+1}: Melhor Fitness = {melhor_fitness}")
    
    return melhor_solucao, melhor_fitness

# Função para determinar a ordem de carregamento
def ordem_de_carregamento(cromossomo):
    slots_ordenados = np.argsort(cromossomo[1])
    ordem = cromossomo[0, slots_ordenados]
    return ordem

# Parâmetros do AG
tam_pop = 10  # tamanho da população
geracoes = 50  # número de gerações
taxa_mutacao = 0.01  # taxa de mutação
k_torneio = 3  # número de competidores no torneio

# Execução do Algoritmo Genético
melhor_solucao, melhor_fitness = algoritmo_genetico(tam_pop, n_conteiners, m_slots, geracoes, taxa_mutacao, k_torneio)

print("Melhor solução encontrada:")
print(melhor_solucao)
print("Melhor fitness:", melhor_fitness)

# Determinar e exibir a ordem de carregamento
ordem = ordem_de_carregamento(melhor_solucao)
print("Ordem de carregamento:", ordem)


Geração 1: Melhor Fitness = 435
Geração 2: Melhor Fitness = 435
Geração 3: Melhor Fitness = 435
Geração 4: Melhor Fitness = 435
Geração 5: Melhor Fitness = 435
Geração 6: Melhor Fitness = 435
Geração 7: Melhor Fitness = 435
Geração 8: Melhor Fitness = 435
Geração 9: Melhor Fitness = 435
Geração 10: Melhor Fitness = 435
Geração 11: Melhor Fitness = 435
Geração 12: Melhor Fitness = 435
Geração 13: Melhor Fitness = 435
Geração 14: Melhor Fitness = 435
Geração 15: Melhor Fitness = 435
Geração 16: Melhor Fitness = 435
Geração 17: Melhor Fitness = 435
Geração 18: Melhor Fitness = 435
Geração 19: Melhor Fitness = 435
Geração 20: Melhor Fitness = 435
Geração 21: Melhor Fitness = 435
Geração 22: Melhor Fitness = 435
Geração 23: Melhor Fitness = 435
Geração 24: Melhor Fitness = 435
Geração 25: Melhor Fitness = 435
Geração 26: Melhor Fitness = 435
Geração 27: Melhor Fitness = 435
Geração 28: Melhor Fitness = 435
Geração 29: Melhor Fitness = 435
Geração 30: Melhor Fitness = 435
Geração 31: Melhor 

In [12]:
def simular_carregamento(cromossomo, n_andar, n_linha, n_coluna):
    matriz = np.zeros((n_andar, n_linha, n_coluna), dtype=int)
    
    slots_ordenados = np.argsort(cromossomo[1])
    ordem_conteiners = cromossomo[0, slots_ordenados]
    ordem_slots = cromossomo[1, slots_ordenados]
    
    for conteiner, slot in zip(ordem_conteiners, ordem_slots):
        andar = slot // (n_linha * n_coluna)
        linha = (slot % (n_linha * n_coluna)) // n_coluna
        coluna = (slot % (n_linha * n_coluna)) % n_coluna
        matriz[andar, linha, coluna] = 1
        
        print(f"Após colocar contêiner {conteiner} no slot {slot}:")
        print(matriz)
        print()

simular_carregamento(melhor_solucao, 3,4,3 )

Após colocar contêiner 8 no slot 0:
[[[1 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]]

Após colocar contêiner 29 no slot 1:
[[[1 1 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]]

Após colocar contêiner 6 no slot 2:
[[[1 1 1]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]]

Após colocar contêiner 19 no slot 3:
[[[1 1 1]
  [1 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]]

Após colocar contêiner 24 no slot 4:
[[[1 1 1]
  [1 1 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]]

Após colocar contêiner 15 no slot 5:
[[[1 1 1]
  [1 1 1]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]]

Após colocar contê