### Cromossomo e população:

In [6]:
import random
import pandas as pd

def gerar_cromossomo():
    cromossomo = []
    
    # Gera posições iniciais (0-29)
    posicoes_iniciais = list(range(1, 31))
    random.shuffle(posicoes_iniciais)
    cromossomo.extend(posicoes_iniciais)
    
    # Gera posições finais (30-59)
    posicoes_finais = list(range(1, 31))
    random.shuffle(posicoes_finais)
    cromossomo.extend(posicoes_finais)
    
    # Gera ordem de movimentação (60-89)
    ordem_movimentacao = list(range(1, 31))
    random.shuffle(ordem_movimentacao)
    cromossomo.extend(ordem_movimentacao)
    
    return cromossomo

def cromossomo_para_dataframe(cromossomo):
    container = list(range(30))
    posicao_inicial = cromossomo[:30]
    posicao_final = cromossomo[30:60]
    ordem_movimentacao = cromossomo[60:90]
    
    df = pd.DataFrame({
        'Container': container,
        'Posição Inicial': posicao_inicial,
        'Posição Final': posicao_final,
        'Ordem de Movimentação': ordem_movimentacao
    })
    
    # Ordenar o DataFrame pela coluna 'Ordem de Movimentação'
    df = df.sort_values(by='Ordem de Movimentação')
    
    return df

def inicializar_populacao(tamanho_populacao):
    populacao = []
    for _ in range(tamanho_populacao):
        cromossomo = gerar_cromossomo()
        populacao.append(cromossomo)
    return populacao

# Teste da inicialização da população
tamanho_populacao = 10
populacao_inicial = inicializar_populacao(tamanho_populacao)
'''
# Exibe a população inicial
for i, cromossomo in enumerate(populacao_inicial):
    print(f"Cromossomo {i + 1}: {cromossomo}")
'''
# Teste da função cromossomo_para_dataframe
cromossomo_exemplo = populacao_inicial[0]
df_cromossomo = cromossomo_para_dataframe(cromossomo_exemplo)
print("DataFrame do Cromossomo:")
print(df_cromossomo)


DataFrame do Cromossomo:
    Container  Posição Inicial  Posição Final  Ordem de Movimentação
13         13               24             27                      1
0           0               21              3                      2
5           5                3             17                      3
3           3               12              9                      4
23         23                5             18                      5
9           9                4             30                      6
16         16                7             26                      7
29         29               28             28                      8
26         26               30             10                      9
10         10               17             20                     10
14         14               23              7                     11
11         11               10             25                     12
2           2               29             29                     13
27       

### Criando a balsa e o porto:



In [7]:
import random
import numpy as np
import pandas as pd

def gerar_cromossomo():
    cromossomo = []
    
    # Gera posições iniciais (0-29)
    posicoes_iniciais = list(range(1, 31))
    random.shuffle(posicoes_iniciais)
    cromossomo.extend(posicoes_iniciais)
    
    # Gera posições finais (30-59)
    posicoes_finais = list(range(1, 31))
    random.shuffle(posicoes_finais)
    cromossomo.extend(posicoes_finais)
    
    # Gera ordem de movimentação (60-89)
    ordem_movimentacao = list(range(1, 31))
    random.shuffle(ordem_movimentacao)
    cromossomo.extend(ordem_movimentacao)
    
    return cromossomo
    
def cromossomo_para_dataframe(cromossomo):
    container = list(range(30))
    posicao_inicial = cromossomo[:30]
    posicao_final = cromossomo[30:60]
    ordem_movimentacao = cromossomo[60:90]
    
    df = pd.DataFrame({
        'Container': container,
        'Posição Inicial': posicao_inicial,
        'Posição Final': posicao_final,
        'Ordem de Movimentação': ordem_movimentacao
    })
    
    # Ordenar o DataFrame pela coluna 'Ordem de Movimentação'
    df = df.sort_values(by='Ordem de Movimentação')
    
    return df

def inicializar_populacao(tamanho_populacao):
    populacao = []
    for _ in range(tamanho_populacao):
        cromossomo = gerar_cromossomo()
        populacao.append(cromossomo)
    return populacao

def preencher_porto_balsa(cromossomo):
    # Inicializar o porto como um array 3D de zeros
    porto = np.zeros((2, 5, 3), dtype=int)
    balsa = np.zeros((3, 4, 3), dtype=int)
    ordem_inicial = []
    ordem_final = []

    cromossomo = cromossomo.sort_values(by='Posição Inicial')
    for _, linha in cromossomo.iterrows():  # Itera sobre as linhas do DataFrame
        ordem_inicial.append(linha['Container'])
    idx = 0
    for andar in range(2):
        for x in range(5):
            for y in range(3):
                if idx < 30:
                    porto[andar, x, y] = ordem_inicial[idx]
                    idx += 1

    cromossomo = cromossomo.sort_values(by='Posição Final')
    for _, linha in cromossomo.iterrows():  # Itera sobre as linhas do DataFrame
        ordem_final.append(linha['Container'])
    idx = 0
    for andar in range(3):
        for x in range(4):
            for y in range(3):
                if idx < 30:
                    balsa[andar, x, y] = ordem_final[idx]
                    idx += 1
                
    return porto, balsa


# Teste da inicialização da população
tamanho_populacao = 10
populacao_inicial = inicializar_populacao(tamanho_populacao)

# Exibir um exemplo de cromossomo e o porto inicial
cromossomo_exemplo = populacao_inicial[0]


df_cromossomo = cromossomo_para_dataframe(cromossomo_exemplo)
print("DataFrame do Cromossomo:")
print(df_cromossomo)

porto, balsa = preencher_porto_balsa(df_cromossomo)

print("\nPorto Inicial (andar 0):")
print(porto[0])
print("\nPorto Inicial (andar 1):")
print(porto[1])

print("\nBalsa (andar 0):")
print(balsa[0])
print("\nBalsa (andar 1):")
print(balsa[1])
print("\nBalsa (andar 2):")
print(balsa[2])



DataFrame do Cromossomo:
    Container  Posição Inicial  Posição Final  Ordem de Movimentação
28         28               19             25                      1
11         11               29             26                      2
2           2               22              3                      3
16         16               21             24                      4
18         18               15             21                      5
12         12               14             27                      6
24         24               16              8                      7
14         14                2             20                      8
8           8                7             23                      9
5           5                1             13                     10
19         19                4             28                     11
6           6                5             10                     12
4           4               18             17                     13
22       

### Movimentação printando funcionado

In [9]:
import random
import numpy as np
import pandas as pd

def gerar_cromossomo():
    cromossomo = []
    
    # Gera posições iniciais (1-30)
    posicoes_iniciais = list(range(1, 31))
    random.shuffle(posicoes_iniciais)
    cromossomo.extend(posicoes_iniciais)
    
    # Gera posições finais (1-30)
    posicoes_finais = list(range(1, 31))
    random.shuffle(posicoes_finais)
    cromossomo.extend(posicoes_finais)
    
    # Gera ordem de movimentação (1-30)
    ordem_movimentacao = list(range(1, 31))
    random.shuffle(ordem_movimentacao)
    cromossomo.extend(ordem_movimentacao)
    
    return cromossomo
    
def cromossomo_para_dataframe(cromossomo):
    container = list(range(30))
    posicao_inicial = cromossomo[:30]
    posicao_final = cromossomo[30:60]
    ordem_movimentacao = cromossomo[60:90]
    
    df = pd.DataFrame({
        'Container': container,
        'Posição Inicial': posicao_inicial,
        'Posição Final': posicao_final,
        'Ordem de Movimentação': ordem_movimentacao
    })
    
    # Ordenar o DataFrame pela coluna 'Ordem de Movimentação'
    df = df.sort_values(by='Ordem de Movimentação')
    
    return df

def inicializar_populacao(tamanho_populacao):
    populacao = []
    for _ in range(tamanho_populacao):
        cromossomo = gerar_cromossomo()
        populacao.append(cromossomo)
    return populacao

def preencher_porto(df_cromossomo):
    # Inicializar o porto e balsa
    porto = np.zeros((2, 5, 3), dtype=int)
    balsa = np.zeros((3, 4, 3), dtype=int)
    porto_preenchido = np.ones((2, 5, 3), dtype=int)
    
    
    # Preencher o porto com os dados do cromossomo
    ordem_inicial = []
    ordem_final = []
    

    df_cromossomo = df_cromossomo.sort_values(by='Posição Inicial')
    for _, linha in df_cromossomo.iterrows():
        ordem_inicial.append(linha['Container'])
    idx = 0
    for andar in range(2):
        for x in range(5):
            for y in range(3):
                if idx < 30:
                    porto[andar, x, y] = ordem_inicial[idx]
                    idx += 1
    
    df_cromossomo = df_cromossomo.sort_values(by='Ordem de Movimentação')
    # Realizar movimentações
    for _, linha in df_cromossomo.iterrows():
        container = linha['Container']
        a_pos_inicial = linha['Posição Inicial']
        a_pos_final = linha['Posição Final']
        pos_inicial = linha['Posição Inicial'] - 1
        pos_final = linha['Posição Final'] - 1
        
        andar_ini, x_ini, y_ini = pos_inicial // 15, (pos_inicial % 15) // 3, (pos_inicial % 15) % 3
        andar_fin, x_fin, y_fin = pos_final // 12, (pos_final % 12) // 3, (pos_final % 12) % 3
        
        # Verificar se podemos remover do porto preenchido
        pode_mover = True
        if andar_ini < 1:
            if porto_preenchido[andar_ini + 1, x_ini, y_ini] == 1:
                pode_mover = False
        
        # Verificar se podemos adicionar à balsa
        if andar_fin > 0:
            if balsa[andar_fin - 1, x_fin, y_fin] == 0:
                pode_mover = False
        
        if pode_mover:
            # Atualizar porto_preenchido e balsa
            porto_preenchido[andar_ini, x_ini, y_ini] = 0
            balsa[andar_fin, x_fin, y_fin] = 1
            
            print(f"Movendo container {container} de ({a_pos_inicial})({andar_ini}, {x_ini}, {y_ini}) para ({a_pos_final})({andar_fin}, {x_fin}, {y_fin})")
            print("Estado atual do Porto Preenchido:")
            print(porto_preenchido)
            print("Estado atual da Balsa:")
            print(balsa)
            print("\n")
        else:
            print(f"não moveu container {container} de ({a_pos_inicial})({andar_ini}, {x_ini}, {y_ini}) para ({a_pos_final})({andar_fin}, {x_fin}, {y_fin})")

    return porto, porto_preenchido, balsa

# Teste da inicialização da população
tamanho_populacao = 10
populacao_inicial = inicializar_populacao(tamanho_populacao)

# Exibir um exemplo de cromossomo e o porto inicial
cromossomo_exemplo = populacao_inicial[0]

df_cromossomo = cromossomo_para_dataframe(cromossomo_exemplo)
print("DataFrame do Cromossomo:")
print(df_cromossomo)

porto, porto_preenchido, balsa = preencher_porto(df_cromossomo)

print("\nPorto Inicial (andar 0):")
print(porto[0])
print("\nPorto Inicial (andar 1):")
print(porto[1])

print("\nPorto Preenchido (andar 0):")
print(porto_preenchido[0])
print("\nPorto Preenchido (andar 1):")
print(porto_preenchido[1])

print("\nBalsa (andar 0):")
print(balsa[0])
print("\nBalsa (andar 1):")
print(balsa[1])
print("\nBalsa (andar 2):")
print(balsa[2])




DataFrame do Cromossomo:
    Container  Posição Inicial  Posição Final  Ordem de Movimentação
20         20               21              2                      1
14         14               14             12                      2
21         21               25              8                      3
4           4                3             19                      4
3           3               22             29                      5
27         27               18              1                      6
18         18               30              4                      7
6           6               27             17                      8
24         24                7             22                      9
29         29               12             28                     10
9           9                4             11                     11
22         22               16             14                     12
26         26               24             24                     13
17       

### Movimentação tentando calcular

In [7]:
import random
import numpy as np
import pandas as pd

def gerar_cromossomo():
    cromossomo = []
    
    # Gera posições iniciais (1-30)
    posicoes_iniciais = list(range(1, 31))
    random.shuffle(posicoes_iniciais)
    cromossomo.extend(posicoes_iniciais)
    
    # Gera posições finais (1-30)
    posicoes_finais = list(range(1, 31))
    random.shuffle(posicoes_finais)
    cromossomo.extend(posicoes_finais)
    
    # Gera ordem de movimentação (1-30)
    ordem_movimentacao = list(range(1, 31))
    random.shuffle(ordem_movimentacao)
    cromossomo.extend(ordem_movimentacao)
    
    return cromossomo
    
def cromossomo_para_dataframe(cromossomo):
    container = list(range(30))
    posicao_inicial = cromossomo[:30]
    posicao_final = cromossomo[30:60]
    ordem_movimentacao = cromossomo[60:90]
    
    df = pd.DataFrame({
        'Container': container,
        'Posição Inicial': posicao_inicial,
        'Posição Final': posicao_final,
        'Ordem de Movimentação': ordem_movimentacao
    })
    
    # Ordenar o DataFrame pela coluna 'Ordem de Movimentação'
    df = df.sort_values(by='Ordem de Movimentação')
    
    return df

def inicializar_populacao(tamanho_populacao):
    populacao = []
    for _ in range(tamanho_populacao):
        cromossomo = gerar_cromossomo()
        populacao.append(cromossomo)
    return populacao

def preencher_porto(df_cromossomo):
    # Inicializar o porto e balsa
    porto = np.zeros((2, 5, 3), dtype=int)
    balsa = np.zeros((3, 4, 3), dtype=int)
    porto_preenchido = np.ones((2, 5, 3), dtype=int)
    cal_movimentos = 0
    
    
    # Preencher o porto com os dados do cromossomo
    ordem_inicial = []
    ordem_final = []
    

    df_cromossomo = df_cromossomo.sort_values(by='Posição Inicial')
    for _, linha in df_cromossomo.iterrows():
        ordem_inicial.append(linha['Container'])
    idx = 0
    for andar in range(2):
        for x in range(5):
            for y in range(3):
                if idx < 30:
                    porto[andar, x, y] = ordem_inicial[idx]
                    idx += 1
    
    df_cromossomo = df_cromossomo.sort_values(by='Ordem de Movimentação')
    # Realizar movimentações
    for _, linha in df_cromossomo.iterrows():
        container = linha['Container']
        a_pos_inicial = linha['Posição Inicial']
        a_pos_final = linha['Posição Final']
        pos_inicial = linha['Posição Inicial'] - 1
        pos_final = linha['Posição Final'] - 1
        
        andar_ini, x_ini, y_ini = pos_inicial // 15, (pos_inicial % 15) // 3, (pos_inicial % 15) % 3
        andar_fin, x_fin, y_fin = pos_final // 12, (pos_final % 12) // 3, (pos_final % 12) % 3
        
        # Verificar se podemos remover do porto preenchido
        pode_mover = True
        if andar_ini < 1:
            if porto_preenchido[andar_ini + 1, x_ini, y_ini] == 1:
                pode_mover = False
        
        # Verificar se podemos adicionar à balsa
        if andar_fin > 0:
            if balsa[andar_fin - 1, x_fin, y_fin] == 0:
                pode_mover = False
        
        if pode_mover:
            # Atualizar porto_preenchido e balsa
            porto_preenchido[andar_ini, x_ini, y_ini] = 0
            balsa[andar_fin, x_fin, y_fin] = 1
            cal_movimentos +=1
            
            '''print(f"Movendo container {container} de ({a_pos_inicial})({andar_ini}, {x_ini}, {y_ini}) para ({a_pos_final})({andar_fin}, {x_fin}, {y_fin})")
            print("Estado atual do Porto Preenchido:")
            print(porto_preenchido)
            print("Estado atual da Balsa:")
            print(balsa)
            print("\n")'''
        else:
            cal_movimentos +=1000
            #print(f"não moveu container {container} de ({a_pos_inicial})({andar_ini}, {x_ini}, {y_ini}) para ({a_pos_final})({andar_fin}, {x_fin}, {y_fin})")

    return cal_movimentos

# Teste da inicialização da população
tamanho_populacao = 100
populacao_inicial = inicializar_populacao(tamanho_populacao)

fitness =[]
melhor_fit = float('inf')  # Inicializa com um valor muito grande para garantir que o primeiro fit encontrado seja menor

for i, cromossomo_exemplo in enumerate(populacao_inicial):
    df_cromossomo = cromossomo_para_dataframe(cromossomo_exemplo)
    fit = preencher_porto(df_cromossomo)
    #print(f"Cromossomo {i} tem {fit} movimentações")
    
    if fit < melhor_fit:
        melhor_fit = fit

print(f"O menor fit encontrado é: {melhor_fit}")



O menor fit encontrado é: 11019


### Seleção, Cruzamento e Mutação

In [1]:
import random
import numpy as np
import pandas as pd

def gerar_cromossomo():
    cromossomo = []
    
    # Gera posições iniciais (0-29)
    posicoes_iniciais = list(range(30))
    random.shuffle(posicoes_iniciais)
    cromossomo.extend(posicoes_iniciais)
    
    # Gera posições finais (0-29)
    posicoes_finais = list(range(30))
    random.shuffle(posicoes_finais)
    cromossomo.extend(posicoes_finais)
    
    # Gera ordem de movimentação (0-29)
    ordem_movimentacao = list(range(30))
    random.shuffle(ordem_movimentacao)
    cromossomo.extend(ordem_movimentacao)
    
    return cromossomo

def cromossomo_para_dataframe(cromossomo):
    container = list(range(30))
    posicao_inicial = cromossomo[:30]
    posicao_final = cromossomo[30:60]
    ordem_movimentacao = cromossomo[60:90]
    
    df = pd.DataFrame({
        'Container': container,
        'Posição Inicial': posicao_inicial,
        'Posição Final': posicao_final,
        'Ordem de Movimentação': ordem_movimentacao
    })
    
    # Ordenar o DataFrame pela coluna 'Ordem de Movimentação'
    df = df.sort_values(by='Ordem de Movimentação')
    
    return df

def inicializar_populacao(tamanho_populacao):
    populacao = []
    for _ in range(tamanho_populacao):
        cromossomo = gerar_cromossomo()
        populacao.append(cromossomo)
    return populacao

def verifica_repetidos(cromossomo):
    intervalos = [
        (0, 29),
        (30, 59),
        (60, 89)
    ]
    
    for intervalo in intervalos:
        valores = cromossomo[intervalo[0]:intervalo[1]+1]
        if len(valores) != len(set(valores)):
            return True
    
    return False

def preencher_porto(df_cromossomo):
    # Inicializar o porto e balsa
    porto = np.zeros((2, 5, 3), dtype=int)
    balsa = np.zeros((3, 4, 3), dtype=int)
    porto_preenchido = np.ones((2, 5, 3), dtype=int)
    cal_movimentos = 0
    
    # Preencher o porto com os dados do cromossomo
    ordem_inicial = []
    ordem_final = []

    df_cromossomo = df_cromossomo.sort_values(by='Posição Inicial')
    for _, linha in df_cromossomo.iterrows():
        ordem_inicial.append(linha['Container'])
    idx = 0
    for andar in range(2):
        for x in range(5):
            for y in range(3):
                if idx < 30:
                    porto[andar, x, y] = ordem_inicial[idx]
                    idx += 1
    
    df_cromossomo = df_cromossomo.sort_values(by='Ordem de Movimentação')
    # Realizar movimentações
    for _, linha in df_cromossomo.iterrows():
        container = linha['Container']
        a_pos_inicial = linha['Posição Inicial']
        a_pos_final = linha['Posição Final']
        pos_inicial = linha['Posição Inicial'] - 1
        pos_final = linha['Posição Final'] - 1
        
        andar_ini, x_ini, y_ini = pos_inicial // 15, (pos_inicial % 15) // 3, (pos_inicial % 15) % 3
        andar_fin, x_fin, y_fin = pos_final // 12, (pos_final % 12) // 3, (pos_final % 12) % 3
        
        # Verificar se podemos remover do porto preenchido
        pode_mover = True
        if andar_ini < 1:
            if porto_preenchido[andar_ini + 1, x_ini, y_ini] == 1:
                pode_mover = False
        

            if porto_preenchido[andar_ini + 1, x_ini, y_ini] == 1:
                pode_mover = False
        
        # Verificar se podemos adicionar à balsa
        if andar_fin > 0:
            if balsa[andar_fin - 1, x_fin, y_fin] == 0:
                pode_mover = False


                
        if pode_mover:
            # Atualizar porto_preenchido e balsa
            porto_preenchido[andar_ini, x_ini, y_ini] = 0
            balsa[andar_fin, x_fin, y_fin] = 1
            cal_movimentos += (
                              ((3-andar_ini)+(3-andar_fin)) #alturas
                              + (abs(x_ini - x_fin))
                              + ((2-y_ini)+(y_fin))
                              )
        else:
            cal_movimentos += 1000
            

    return cal_movimentos

def torneio(populacao, fitness, k=3):
    selecionados = random.sample(list(zip(populacao, fitness)), k)
    selecionados.sort(key=lambda x: x[1])
    return selecionados[0][0]

def cruzamento(pai, mae):
    ponto_corte = random.randint(1, 29)
    
    filho1 = pai[:ponto_corte] + mae[ponto_corte:30]
    filho2 = mae[:ponto_corte] + pai[ponto_corte:30]
    
    ponto_corte = random.randint(31, 59)
    
    filho1 += pai[30:ponto_corte] + mae[ponto_corte:60]
    filho2 += mae[30:ponto_corte] + pai[ponto_corte:60]
    
    ponto_corte = random.randint(61, 89)
    
    filho1 += pai[60:ponto_corte] + mae[ponto_corte:90]
    filho2 += mae[60:ponto_corte] + pai[ponto_corte:90]
    
    return filho1, filho2

def mutacao(cromossomo, taxa_mutacao=0.01):
    if random.random() < taxa_mutacao:
        part = random.randint(0, 2)
        idx1, idx2 = random.sample(range(30), 2)
        if part == 0:
            cromossomo[idx1], cromossomo[idx2] = cromossomo[idx2], cromossomo[idx1]
        elif part == 1:
            cromossomo[30+idx1], cromossomo[30+idx2] = cromossomo[30+idx2], cromossomo[30+idx1]
        else:
            cromossomo[60+idx1], cromossomo[60+idx2] = cromossomo[60+idx2], cromossomo[60+idx1]
    return cromossomo

def algoritmo_genetico(tamanho_populacao, geracoes, taxa_mutacao=0.01):
    populacao = inicializar_populacao(tamanho_populacao)
    fitness = [preencher_porto(cromossomo_para_dataframe(cromossomo)) for cromossomo in populacao]
    
    for geracao in range(geracoes):
        nova_populacao = []
        while len(nova_populacao) < tamanho_populacao:
            pai = torneio(populacao, fitness)
            mae = torneio(populacao, fitness)
            
            filho1, filho2 = cruzamento(pai, mae)
            filho1 = mutacao(filho1, taxa_mutacao)
            filho2 = mutacao(filho2, taxa_mutacao)
            
            nova_populacao.append(filho1)
            nova_populacao.append(filho2)
        
        populacao = nova_populacao[:tamanho_populacao]
        fitness = [preencher_porto(cromossomo_para_dataframe(cromossomo)) for cromossomo in populacao]
        
        melhor_fit = min(fitness)
        print(f"Geração {geracao+1}: Melhor fitness = {melhor_fit}")
    
    melhor_cromossomo = populacao[fitness.index(min(fitness))]
    return melhor_cromossomo, min(fitness)

# Configurações
tamanho_populacao = 100
geracoes = 200
taxa_mutacao = 0.05

melhor_cromossomo, melhor_fit = algoritmo_genetico(tamanho_populacao, geracoes, taxa_mutacao)
print(f"Melhor cromossomo encontrado: {melhor_cromossomo}")
print(f"Melhor fitness: {melhor_fit}")


Geração 1: Melhor fitness = 12144
Geração 2: Melhor fitness = 12141
Geração 3: Melhor fitness = 10160
Geração 4: Melhor fitness = 8194
Geração 5: Melhor fitness = 7198
Geração 6: Melhor fitness = 7186
Geração 7: Melhor fitness = 6202
Geração 8: Melhor fitness = 4211
Geração 9: Melhor fitness = 4220
Geração 10: Melhor fitness = 3222
Geração 11: Melhor fitness = 4220
Geração 12: Melhor fitness = 3217
Geração 13: Melhor fitness = 2231
Geração 14: Melhor fitness = 3219
Geração 15: Melhor fitness = 2230
Geração 16: Melhor fitness = 2235
Geração 17: Melhor fitness = 2226
Geração 18: Melhor fitness = 2225
Geração 19: Melhor fitness = 1238
Geração 20: Melhor fitness = 1229
Geração 21: Melhor fitness = 1230
Geração 22: Melhor fitness = 1225
Geração 23: Melhor fitness = 1223
Geração 24: Melhor fitness = 1223
Geração 25: Melhor fitness = 1223
Geração 26: Melhor fitness = 1222
Geração 27: Melhor fitness = 1221
Geração 28: Melhor fitness = 1216
Geração 29: Melhor fitness = 1216
Geração 30: Melhor f

#### Verifica se ha numeros repetidos


In [4]:
def verifica_repetidos(cromossomo):
    intervalos = [
        (0, 29),
        (30, 59),
        (60, 89)
    ]
    
    for intervalo in intervalos:
        valores = cromossomo[intervalo[0]:intervalo[1]+1]
        if len(valores) != len(set(valores)):
            return True
    
    return False

cromossomo = [21, 6, 27, 21, 26, 21, 21, 21, 20, 24, 21, 21, 26, 27, 16, 21, 12, 26, 24, 21, 21, 20, 24, 24, 21, 21, 24, 21, 18, 21, 16, 29, 12, 16, 23, 4, 16, 16, 28, 20, 4, 29, 10, 11, 2, 4, 23, 10, 16, 28, 16, 4, 8, 20, 16, 16, 5, 17, 1, 16, 20, 26, 7, 1, 21, 0, 23, 17, 9, 25, 6, 24, 0, 2, 9, 15, 20, 4, 19, 26, 22, 0, 4, 10, 24, 2, 4, 21, 12, 15]

if verifica_repetidos(cromossomo):
    print("Valores repetidos encontrados!")
else:
    print("Não há valores repetidos.")

Valores repetidos encontrados!


### Simular Melhor cromomossomo

In [18]:
def Simular_preencher_porto(df_cromossomo):
    # Inicializar o porto e balsa
    porto = np.zeros((2, 5, 3), dtype=int)
    balsa = np.zeros((3, 4, 3), dtype=int)
    porto_preenchido = np.ones((2, 5, 3), dtype=int)
    
    
    # Preencher o porto com os dados do cromossomo
    ordem_inicial = []
    ordem_final = []
    

    df_cromossomo = df_cromossomo.sort_values(by='Posição Inicial')
    for _, linha in df_cromossomo.iterrows():
        ordem_inicial.append(linha['Container'])
    idx = 0
    for andar in range(2):
        for x in range(5):
            for y in range(3):
                if idx < 30:
                    porto[andar, x, y] = ordem_inicial[idx]
                    idx += 1
    
    df_cromossomo = df_cromossomo.sort_values(by='Ordem de Movimentação')
    # Realizar movimentações
    for _, linha in df_cromossomo.iterrows():
        container = linha['Container']
        a_pos_inicial = linha['Posição Inicial']
        a_pos_final = linha['Posição Final']
        pos_inicial = linha['Posição Inicial'] - 1
        pos_final = linha['Posição Final'] - 1
        
        andar_ini, x_ini, y_ini = pos_inicial // 15, (pos_inicial % 15) // 3, (pos_inicial % 15) % 3
        andar_fin, x_fin, y_fin = pos_final // 12, (pos_final % 12) // 3, (pos_final % 12) % 3
        
        # Verificar se podemos remover do porto preenchido
        pode_mover = True
        if andar_ini < 1:
            if porto_preenchido[andar_ini + 1, x_ini, y_ini] == 1:
                pode_mover = False
        
        # Verificar se podemos adicionar à balsa
        if andar_fin > 0:
            if balsa[andar_fin - 1, x_fin, y_fin] == 0:
                pode_mover = False
        
        if pode_mover:
            # Atualizar porto_preenchido e balsa
            porto_preenchido[andar_ini, x_ini, y_ini] = 0
            balsa[andar_fin, x_fin, y_fin] = 1
            
            print(f"Movendo container {container} de ({a_pos_inicial})({andar_ini}, {x_ini}, {y_ini}) para ({a_pos_final})({andar_fin}, {x_fin}, {y_fin})")
            print("Estado atual do Porto Preenchido:")
            print(porto_preenchido)
            print("Estado atual da Balsa:")
            print(balsa)
            print("\n")
        else:
            print(f"não moveu container {container} de ({a_pos_inicial})({andar_ini}, {x_ini}, {y_ini}) para ({a_pos_final})({andar_fin}, {x_fin}, {y_fin})")


Simular_preencher_porto(cromossomo_para_dataframe(melhor_cromossomo))

Movendo container 28 de (26)(1, 3, 1) para (12)(0, 3, 2)
Estado atual do Porto Preenchido:
[[[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 0 1]
  [1 1 1]]]
Estado atual da Balsa:
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 1]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


Movendo container 8 de (25)(1, 3, 0) para (7)(0, 2, 0)
Estado atual do Porto Preenchido:
[[[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [0 0 1]
  [1 1 1]]]
Estado atual da Balsa:
[[[0 0 0]
  [0 0 0]
  [1 0 0]
  [0 0 1]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


Movendo container 12 de (22)(1, 2, 0) para (3)(0, 0, 2)
Estado atual do Porto Preenchido:
[[[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [0 1 1]
  [0 0 1]
  [1 1 1]]]
Estado atual da Balsa:
[[[0 0 1]
  [0 0 0]
  [1 0 0]
  [0 0 1]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]