# Cromossomo

In [1]:
import numpy as np

class CarregamentoContêinerGA:
    def __init__(self, num_conteineres, num_slots):
        self.num_conteineres = num_conteineres
        self.num_slots = num_slots
        self.conteineres = np.arange(num_conteineres)
        self.slots = np.arange(num_slots)
        np.random.shuffle(self.slots)
    
    def criar_cromossomo(self):
        cromossomo = np.zeros((2, self.num_conteineres), dtype=int)
        cromossomo[0] = self.conteineres
        cromossomo[1] = np.random.choice(self.slots, self.num_conteineres, replace=False)
        return cromossomo
    
    def decodificar_cromossomo(self, cromossomo):
        ordem_conteineres = cromossomo[0]
        atribuicao_slots = cromossomo[1]
        decodificado = {conteiner: slot for conteiner, slot in zip(ordem_conteineres, atribuicao_slots)}
        return decodificado

# Exemplo de uso:
num_conteineres = 14
num_slots = 20

ga = CarregamentoContêinerGA(num_conteineres, num_slots)
cromossomo = ga.criar_cromossomo()
decodificado = ga.decodificar_cromossomo(cromossomo)

print("Cromossomo:")
print(cromossomo)
print("\nDecodificação:")
print(decodificado)


Cromossomo:
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
 [10  7  1  4  8 18  6 15 16  9  5  2 12 14]]

Decodificação:
{0: 10, 1: 7, 2: 1, 3: 4, 4: 8, 5: 18, 6: 6, 7: 15, 8: 16, 9: 9, 10: 5, 11: 2, 12: 12, 13: 14}


# 4.4 população  

In [2]:
import numpy as np

class CarregamentoConteinerGA:
    def __init__(self, num_conteineres, num_slots, tam_populacao):
        self.num_conteineres = num_conteineres
        self.num_slots = num_slots
        self.tam_populacao = tam_populacao
        self.populacao = []
        self.gerar_populacao_inicial()
    
    def gerar_populacao_inicial(self):
        for _ in range(self.tam_populacao):
            cromossomo = self.criar_cromossomo()
            self.populacao.append(cromossomo)
    
    def criar_cromossomo(self):
        cromossomo = np.zeros((2, self.num_conteineres), dtype=int)

        # Dimensão x (contêineres)
        vetor_x = list(range(self.num_conteineres))
        for i in range(self.num_conteineres):
            indice = np.random.randint(0, len(vetor_x))
            cromossomo[0, i] = vetor_x.pop(indice)

        # Dimensão y (slots)
        vetor_y = list(range(self.num_slots))
        for i in range(self.num_conteineres):
            indice = np.random.randint(0, len(vetor_y))
            cromossomo[1, i] = vetor_y.pop(indice)

        return cromossomo
    
    def decodificar_cromossomo(self, cromossomo):
        ordem_conteineres = cromossomo[0]
        atribuicao_slots = cromossomo[1]
        decodificado = {conteiner: slot for conteiner, slot in zip(ordem_conteineres, atribuicao_slots)}
        return decodificado

# Exemplo de uso:
num_conteineres = 14
num_slots = 20
tam_populacao = 10

ga = CarregamentoConteinerGA(num_conteineres, num_slots, tam_populacao)

print("População Inicial:")
for i, cromossomo in enumerate(ga.populacao):
    print(f"Cromossomo {i+1}:")
    print(cromossomo)
    print("\nDecodificação:")
    print(ga.decodificar_cromossomo(cromossomo))
    print()


População Inicial:
Cromossomo 1:
[[ 0  6 13  1  3  2  7  8  9 10 12  5 11  4]
 [ 3 15  5  2  6 12 10 18  4 11 14  9  1  0]]

Decodificação:
{0: 3, 6: 15, 13: 5, 1: 2, 3: 6, 2: 12, 7: 10, 8: 18, 9: 4, 10: 11, 12: 14, 5: 9, 11: 1, 4: 0}

Cromossomo 2:
[[ 1 11  5  4  7  3  6  2  9  8 10 13 12  0]
 [ 0  5 15  6  8 17 11  3 13  4  1 19 18 12]]

Decodificação:
{1: 0, 11: 5, 5: 15, 4: 6, 7: 8, 3: 17, 6: 11, 2: 3, 9: 13, 8: 4, 10: 1, 13: 19, 12: 18, 0: 12}

Cromossomo 3:
[[11  8  0 13  4  3  7 10 12  6  2  5  9  1]
 [19  1 11  0  6  2 12 14  7  4  9 10 16 15]]

Decodificação:
{11: 19, 8: 1, 0: 11, 13: 0, 4: 6, 3: 2, 7: 12, 10: 14, 12: 7, 6: 4, 2: 9, 5: 10, 9: 16, 1: 15}

Cromossomo 4:
[[ 4  0 13 11 12  3  7  2  1  8 10  9  5  6]
 [11  4  0  7 19  9 10  2  5 18 15 16  8 17]]

Decodificação:
{4: 11, 0: 4, 13: 0, 11: 7, 12: 19, 3: 9, 7: 10, 2: 2, 1: 5, 8: 18, 10: 15, 9: 16, 5: 8, 6: 17}

Cromossomo 5:
[[ 3 13  9 10 11 12  1  5  4  2  8  0  7  6]
 [ 6  2  3 12 16 11  9  8 13  1 14  4 18 19]]

Deco

# 4.5 Seleção, cruzamento e mutação 

In [4]:
import numpy as np

class CarregamentoConteinerGA:
    def __init__(self, num_conteineres, num_slots, tam_populacao):
        self.num_conteineres = num_conteineres
        self.num_slots = num_slots
        self.tam_populacao = tam_populacao
        self.populacao = []
        self.gerar_populacao_inicial()
    
    def gerar_populacao_inicial(self):
        for _ in range(self.tam_populacao):
            cromossomo = self.criar_cromossomo()
            self.populacao.append(cromossomo)
    
    def criar_cromossomo(self):
        cromossomo = np.zeros((2, self.num_conteineres), dtype=int)

        # Dimensão x (contêineres)
        vetor_x = list(range(self.num_conteineres))
        for i in range(self.num_conteineres):
            indice = np.random.randint(0, len(vetor_x))
            cromossomo[0, i] = vetor_x.pop(indice)

        # Dimensão y (slots)
        vetor_y = list(range(self.num_slots))
        for i in range(self.num_conteineres):
            indice = np.random.randint(0, len(vetor_y))
            cromossomo[1, i] = vetor_y.pop(indice)

        return cromossomo
    
    def decodificar_cromossomo(self, cromossomo):
        ordem_conteineres = cromossomo[0]
        atribuicao_slots = cromossomo[1]
        decodificado = {conteiner: slot for conteiner, slot in zip(ordem_conteineres, atribuicao_slots)}
        return decodificado
    
    # Operador de Seleção: Método da Roleta
    def selecionar_pais_roleta(self, fitnesses):
        total_fitness = sum(fitnesses)
        probs = [f / total_fitness for f in fitnesses]
        indices_pais = np.random.choice(len(self.populacao), size=2, p=probs)
        pais = [self.populacao[i] for i in indices_pais]
        return pais
    
    # Operador de Cruzamento: PMX com um ponto de corte
    def crossover_pmx(self, pai1, pai2):
        ponto_corte = np.random.randint(0, self.num_conteineres)
        filho1, filho2 = np.copy(pai1), np.copy(pai2)
        
        # Troca PMX para dimensão x
        filho1[0, :ponto_corte], filho2[0, :ponto_corte] = pai2[0, :ponto_corte], pai1[0, :ponto_corte]
        
        # Troca PMX para dimensão y
        filho1[1, :ponto_corte], filho2[1, :ponto_corte] = pai2[1, :ponto_corte], pai1[1, :ponto_corte]
        
        return filho1, filho2
    
    # Operador de Mutação: Permuta simples para dimensão x, mutação aleatória para dimensão y
    def mutacao(self, cromossomo, taxa_mutacao_x, taxa_mutacao_y):
        # Mutação na dimensão x (permuta simples)
        if np.random.rand() < taxa_mutacao_x:
            idx1, idx2 = np.random.choice(self.num_conteineres, size=2, replace=False)
            cromossomo[0, idx1], cromossomo[0, idx2] = cromossomo[0, idx2], cromossomo[0, idx1]
        
        # Mutação na dimensão y (valores aleatórios)
        if np.random.rand() < taxa_mutacao_y:
            idx = np.random.randint(0, self.num_conteineres)
            vetor_y = list(set(range(self.num_slots)) - set(cromossomo[1]))
            novo_valor = np.random.choice(vetor_y)
            cromossomo[1, idx] = novo_valor

        return cromossomo

# Exemplo de uso:
num_conteineres = 14
num_slots = 20
tam_populacao = 10

ga = CarregamentoConteinerGA(num_conteineres, num_slots, tam_populacao)
fitnesses = [1.0 / (i+1) for i in range(tam_populacao)]  # Exemplo de fitnesses

# Seleção de pais
pais = ga.selecionar_pais_roleta(fitnesses)

# Cruzamento
filho1, filho2 = ga.crossover_pmx(pais[0], pais[1])

# Mutação
taxa_mutacao_x = 0.1
taxa_mutacao_y = 0.2
filho1_mutado = ga.mutacao(filho1, taxa_mutacao_x, taxa_mutacao_y)
filho2_mutado = ga.mutacao(filho2, taxa_mutacao_x, taxa_mutacao_y)

print("Pais:")
print(pais[0])
print(pais[1])
print("\nFilhos após cruzamento:")
print(filho1)
print(filho2)
print("\nFilhos após mutação:")
print(filho1_mutado)
print(filho2_mutado)



Pais:
[[ 0 10 13  6  3 11 12  9  5  7  1  2  4  8]
 [ 2  4 15 13  3 17  9  6 12 19 16  0 11  1]]
[[ 0  7 13  5  9 11  8 12  4  6  1  3 10  2]
 [17  6 16 12 18  2 13 10  8  9  7  5  3 14]]

Filhos após cruzamento:
[[ 0  7 13  5  9 11  8 12  4  6  1  2  4  8]
 [17  6 16 12 18  2 13 10  8  9  7  0 11  1]]
[[ 0 10 13  6  3 11 12  9  5  7  1  3 10  2]
 [ 2  4 15 13  3 17  9  6 12 19 16  5  3 14]]

Filhos após mutação:
[[ 0  7 13  5  9 11  8 12  4  6  1  2  4  8]
 [17  6 16 12 18  2 13 10  8  9  7  0 11  1]]
[[ 0 10 13  6  3 11 12  9  5  7  1  3 10  2]
 [ 2  4 15 13  3 17  9  6 12 19 16  5  3 14]]


# 4.6.	Avaliação da Solução (Fitness) e as Restrições

In [6]:
import numpy as np

class CarregamentoConteinerGA:
    def __init__(self, num_conteineres, num_slots, tam_populacao):
        self.num_conteineres = num_conteineres
        self.num_slots = num_slots
        self.tam_populacao = tam_populacao
        self.populacao = []
        self.gerar_populacao_inicial()
    
    def gerar_populacao_inicial(self):
        for _ in range(self.tam_populacao):
            cromossomo = self.criar_cromossomo()
            self.populacao.append(cromossomo)
    
    def criar_cromossomo(self):
        cromossomo = np.zeros((2, self.num_conteineres), dtype=int)

        # Dimensão x (contêineres)
        vetor_x = list(range(self.num_conteineres))
        for i in range(self.num_conteineres):
            indice = np.random.randint(0, len(vetor_x))
            cromossomo[0, i] = vetor_x.pop(indice)

        # Dimensão y (slots)
        vetor_y = list(range(self.num_slots))
        for i in range(self.num_conteineres):
            indice = np.random.randint(0, len(vetor_y))
            cromossomo[1, i] = vetor_y.pop(indice)

        return cromossomo
    
    def decodificar_cromossomo(self, cromossomo):
        ordem_conteineres = cromossomo[0]
        atribuicao_slots = cromossomo[1]
        decodificado = {conteiner: slot for conteiner, slot in zip(ordem_conteineres, atribuicao_slots)}
        return decodificado
    
    # Operador de Seleção: Método da Roleta
    def selecionar_pais_roleta(self, fitnesses):
        total_fitness = sum(fitnesses)
        if total_fitness == 0:
            probs = [1 / len(fitnesses) for _ in fitnesses]
        else:
            probs = [f / total_fitness for f in fitnesses]
        indices_pais = np.random.choice(len(self.populacao), size=2, p=probs)
        pais = [self.populacao[i] for i in indices_pais]
        return pais
    
    # Operador de Cruzamento: PMX com um ponto de corte
    def crossover_pmx(self, pai1, pai2):
        ponto_corte = np.random.randint(0, self.num_conteineres)
        filho1, filho2 = np.copy(pai1), np.copy(pai2)
        
        # Troca PMX para dimensão x
        filho1[0, :ponto_corte], filho2[0, :ponto_corte] = pai2[0, :ponto_corte], pai1[0, :ponto_corte]
        
        # Troca PMX para dimensão y
        filho1[1, :ponto_corte], filho2[1, :ponto_corte] = pai2[1, :ponto_corte], pai1[1, :ponto_corte]
        
        return filho1, filho2
    
    # Operador de Mutação: Permuta simples para dimensão x, mutação aleatória para dimensão y
    def mutacao(self, cromossomo, taxa_mutacao_x, taxa_mutacao_y):
        # Mutação na dimensão x (permuta simples)
        if np.random.rand() < taxa_mutacao_x:
            idx1, idx2 = np.random.choice(self.num_conteineres, size=2, replace=False)
            cromossomo[0, idx1], cromossomo[0, idx2] = cromossomo[0, idx2], cromossomo[0, idx1]
        
        # Mutação na dimensão y (valores aleatórios)
        if np.random.rand() < taxa_mutacao_y:
            idx = np.random.randint(0, self.num_conteineres)
            vetor_y = list(set(range(self.num_slots)) - set(cromossomo[1]))
            novo_valor = np.random.choice(vetor_y)
            cromossomo[1, idx] = novo_valor

        return cromossomo
    
    # Função de Fitness
    def calcular_fitness(self, cromossomo):
        fitness = 0
        for c in range(self.num_conteineres):
            fitness += self.calcular_BL(c, cromossomo)
            fitness += self.calcular_DP(c, cromossomo)
            fitness += self.calcular_BP(c, cromossomo)
            fitness += self.calcular_DN(c, cromossomo)
            fitness += self.calcular_VQ(c, cromossomo)
            fitness += self.calcular_OP(c, cromossomo)
        return fitness
    
    def calcular_BL(self, c, cromossomo):
        # Implementar lógica para calcular BL
        return 0  # Exemplo: Retornar 0
    
    def calcular_DP(self, c, cromossomo):
        # Implementar lógica para calcular DP
        return 0  # Exemplo: Retornar 0
    
    def calcular_BP(self, c, cromossomo):
        # Implementar lógica para calcular BP
        return 0  # Exemplo: Retornar 0
    
    def calcular_DN(self, c, cromossomo):
        # Implementar lógica para calcular DN
        return 0  # Exemplo: Retornar 0
    
    def calcular_VQ(self, c, cromossomo):
        # Implementar lógica para calcular VQ
        return 0  # Exemplo: Retornar 0
    
    def calcular_OP(self, c, cromossomo):
        # Implementar lógica para calcular OP
        return 0  # Exemplo: Retornar 0

# Exemplo de uso:
num_conteineres = 14
num_slots = 20
tam_populacao = 10

ga = CarregamentoConteinerGA(num_conteineres, num_slots, tam_populacao)
fitnesses = [ga.calcular_fitness(cromossomo) for cromossomo in ga.populacao]

# Seleção de pais
pais = ga.selecionar_pais_roleta(fitnesses)

# Cruzamento
filho1, filho2 = ga.crossover_pmx(pais[0], pais[1])

# Mutação
taxa_mutacao_x = 0.1
taxa_mutacao_y = 0.2
filho1_mutado = ga.mutacao(filho1, taxa_mutacao_x, taxa_mutacao_y)
filho2_mutado = ga.mutacao(filho2, taxa_mutacao_x, taxa_mutacao_y)

print("Pais:")
print(pais[0])
print(pais[1])
print("\nFilhos após cruzamento:")
print(filho1)
print(filho2)
print("\nFilhos após mutação:")
print(filho1_mutado)
print(filho2_mutado)



Pais:
[[ 6 11  4  7  2 13 12  1  0  9  3 10  8  5]
 [ 8 15  3  5 10 11 19 18  2 16  4  6 13 17]]
[[ 8 13 12  1  6  5  4  3  0  9 11  2  7 10]
 [ 3 16  1 15  9 10 19  0 12 18 13 14  6  8]]

Filhos após cruzamento:
[[ 8 13 12  1  6  5  4  3  0  9  3 10  8  5]
 [ 3 16  1 15  9 10 19  0 12 16  4  6 13 17]]
[[ 6 11  4  7  2 13 12  1  0  9 11  2  7 10]
 [ 8 15  3  5 10 11 19 18  2 18 13 14  6  8]]

Filhos após mutação:
[[ 8 13 12  1  6  5  4  3  0  9  3 10  8  5]
 [ 3 16  1 15  9 10 19  0 12 16  4  6 13 17]]
[[ 6 11  4  7  2 13 12  1  0  9 11  2  7 10]
 [ 8 15  3  5 10 11 19 18  2 18 13 14  6  8]]


In [6]:
import numpy as np

class AlgoritmoGenetico:
    def __init__(self, populacao, dados):
        self.populacao = populacao
        self.dados = dados

    def avaliar_hard_constraints(self, cromossomo):
        penalidade = 0
        
        # 1. Contêiner “flutuando” no navio
        for c in cromossomo:
            if c['slot_flutuando']:
                penalidade += 1000
        
        # 2. Slot inválido para contêiner de 40’
        for c in cromossomo:
            if c['slot_invalido_40']:
                penalidade += 900
        
        # 3. Stacking height
        if sum(c['altura'] for c in cromossomo) > self.dados['MAXAr']:
            penalidade += 500
        
        # 4. Stacking weight
        if sum(c['peso'] for c in cromossomo) > self.dados['MAXPr']:
            penalidade += 500
        
        # 5. Contêiner in-hold
        for c in cromossomo:
            if c['in_hold'] and not c['slot_in_hold']:
                penalidade += 400
        
        # 6. Contêiner reefer
        for c in cromossomo:
            if c['reefer'] and not c['slot_reefer']:
                penalidade += 400
        
        # 7. Contêiner com cargas perigosas
        for c in cromossomo:
            if c['perigoso'] and not c['slot_perigoso']:
                penalidade += 400
        
        # 8. Contêiner OOG
        for c in cromossomo:
            if c['oog'] and not c['slot_oog']:
                penalidade += 400
        
        # 9. Contêiner vazio
        for c in cromossomo:
            if c['vazio'] and not c['slot_vazio']:
                penalidade += 400
        
        # 10. Contêiner planejado para slot específico
        for c in cromossomo:
            if c['especifico'] and not c['slot_especifico']:
                penalidade += 200
        
        # 11. Bay planejada para porto
        for c in cromossomo:
            if c['bay_porto'] and not c['slot_bay_porto']:
                penalidade += 100

        return penalidade

    def avaliar_soft_constraints(self, cromossomo):
        penalidade = 0
        
        # 1. Remoções de pátio
        for c in cromossomo:
            if c['remocoes_de_patio']:
                penalidade += 10
        
        # 2. Distância percorrida pelo recurso de pátio
        penalidade += sum(c['distancia_patio'] for c in cromossomo) * 10
        
        # 3. Contêiner bloqueando movimentação em portos
        for c in cromossomo:
            if c['bloqueio_movimentacao']:
                penalidade += 25
        
        # 4. Distância percorrida pelo recurso de costado
        penalidade += sum(c['distancia_costado'] for c in cromossomo) * 10
        
        # 5. Contêiner de 40’ sobre 20’ (ou inverso)
        for c in cromossomo:
            if c['mismatch_tamanho']:
                penalidade += 10
        
        # 6. Contêiner fora de ordem de peso
        for c in range(1, len(cromossomo)):
            if cromossomo[c]['peso'] > cromossomo[c-1]['peso']:
                penalidade += 15

        return penalidade

    def calcular_fitness(self, cromossomo):
        # Avaliação das restrições imprescindíveis
        penalidade_hard = self.avaliar_hard_constraints(cromossomo)
        
        # Avaliação das restrições desejáveis
        penalidade_soft = self.avaliar_soft_constraints(cromossomo)
        
        # Penalização extra para soluções inválidas
        penalidade_extra = 0
        if penalidade_hard > 0:
            penalidade_extra = len(self.dados['CE']) * 1000
        
        # Fitness final
        fitness = penalidade_hard + penalidade_soft + penalidade_extra
        
        return fitness

    def selecionar_pais_roleta(self, fitnesses):
        total_fitness = sum(fitnesses)
        if total_fitness == 0:
            total_fitness = 1  # Evita divisão por zero
        probs = [f / total_fitness for f in fitnesses]
        indices_pais = np.random.choice(len(self.populacao), size=2, p=probs)
        pais = [self.populacao[i] for i in indices_pais]
        return pais

    def crossover_pmx(self, pai1, pai2):
        # Implementação do crossover PMX
        ponto1, ponto2 = sorted(np.random.choice(len(pai1), 2, replace=False))
        filho1 = pai1[:ponto1] + pai2[ponto1:ponto2] + pai1[ponto2:]
        filho2 = pai2[:ponto1] + pai1[ponto1:ponto2] + pai2[ponto2:]
        return filho1, filho2

    def mutacao(self, cromossomo):
        # Implementação da mutação
        ponto = np.random.randint(len(cromossomo))
        cromossomo[ponto] = np.random.choice(self.dados['CE'])

    def substituir(self, filho1, filho2):
        # Substituição na população
        nova_populacao = self.populacao[:-2] + [filho1, filho2]
        return nova_populacao

def criar_populacao_inicial(dados, POPULACAO_TAMANHO, TAMANHO_CROMOSSOMO):
    populacao = []
    for _ in range(POPULACAO_TAMANHO):
        cromossomo = []
        for _ in range(TAMANHO_CROMOSSOMO):
            # Criar um dicionário representando um contêiner com atributos aleatórios
            cont = {
                'slot_flutuando': bool(np.random.randint(2)),  # Aleatoriamente True ou False
                'slot_invalido_40': bool(np.random.randint(2)), # Aleatoriamente True ou False
                'altura': np.random.randint(10, 50),  # Altura aleatória
                'peso': np.random.randint(50, 150),  # Peso aleatório
                'in_hold': bool(np.random.randint(2)),  # Aleatoriamente True ou False
                'slot_in_hold': bool(np.random.randint(2)),  # Aleatoriamente True ou False
                'reefer': bool(np.random.randint(2)),  # Aleatoriamente True ou False
                'slot_reefer': bool(np.random.randint(2)),  # Aleatoriamente True ou False
                'perigoso': bool(np.random.randint(2)),  # Aleatoriamente True ou False
                'slot_perigoso': bool(np.random.randint(2)),  # Aleatoriamente True ou False
                'oog': bool(np.random.randint(2)),  # Aleatoriamente True ou False
                'slot_oog': bool(np.random.randint(2)),  # Aleatoriamente True ou False
                'vazio': bool(np.random.randint(2)),  # Aleatoriamente True ou False
                'slot_vazio': bool(np.random.randint(2)),  # Aleatoriamente True ou False
                'especifico': bool(np.random.randint(2)),  # Aleatoriamente True ou False
                'slot_especifico': bool(np.random.randint(2)),  # Aleatoriamente True ou False
                'bay_porto': bool(np.random.randint(2)),  # Aleatoriamente True ou False
                'slot_bay_porto': bool(np.random.randint(2))  # Aleatoriamente True ou False
            }
            cromossomo.append(cont)
        populacao.append(cromossomo)
    return populacao


def carregar_dados():
    dados = {
        'CE': [1, 2, 3, 4, 5], # Exemplo de contêineres
        'MAXAr': 100,
        'MAXPr': 200
    }
    return dados

POPULACAO_TAMANHO = 100
TAMANHO_CROMOSSOMO = 5
NUMERO_DE_GERACOES = 50

dados = carregar_dados()
populacao_inicial = AlgoritmoGenetico.criar_populacao_inicial(dados, POPULACAO_TAMANHO, TAMANHO_CROMOSSOMO)

ga = AlgoritmoGenetico(populacao_inicial, dados)

for geracao in range(NUMERO_DE_GERACOES):
    # Avaliar fitness de cada cromossomo na população
    fitnesses = [ga.calcular_fitness(cromossomo) for cromossomo in ga.populacao]
    # Seleção de pais
    pais = ga.selecionar_pais_roleta(fitnesses)

    # Cruzamento
    filho1, filho2 = ga.crossover_pmx(pais[0], pais[1])

    # Mutação
    ga.mutacao(filho1)
    ga.mutacao(filho2)

    # Substituição na população
    ga.populacao = ga.substituir(filho1, filho2)

    # Possivelmente salvar ou imprimir resultados
    print(f'Geração {geracao}: Melhor fitness = {min(fitnesses)}')

    melhor_solucao = min(ga.populacao, key=ga.calcular_fitness)
    print('Melhor solução:', melhor_solucao)



AttributeError: type object 'AlgoritmoGenetico' has no attribute 'criar_populacao_inicial'

In [8]:
import random
import numpy as np

# Definir as dimensões do porto
dim_x, dim_y, num_andar = 3, 5, 2

def gerar_cromossomo():
    cromossomo = []
    
    # Gera posições iniciais (0-29)
    posicoes_iniciais = list(range(1, 31))
    random.shuffle(posicoes_iniciais)
    cromossomo.extend(posicoes_iniciais)
    
    # Gera posições finais (30-59)
    posicoes_finais = list(range(1, 31))
    random.shuffle(posicoes_finais)
    cromossomo.extend(posicoes_finais)
    
    # Gera ordem de movimentação (60-89)
    ordem_movimentacao = list(range(1, 31))
    random.shuffle(ordem_movimentacao)
    cromossomo.extend(ordem_movimentacao)
    
    return cromossomo

def inicializar_populacao(tamanho_populacao):
    populacao = []
    for _ in range(tamanho_populacao):
        cromossomo = gerar_cromossomo()
        populacao.append(cromossomo)
    return populacao

def preencher_porto_balsa(cromossomo):
    # Inicializar o porto como um array 3D de zeros
    porto = np.zeros((3, 5, 2), dtype=int)
    balsa = np.zeros((3, 4, 3), dtype=int)
    
    # Preencher o porto com as posições iniciais dos contêineres (0-29 do cromossomo)
    posicoes_iniciais = cromossomo[:30]
    idx = 0
    for andar in range(2):
        for x in range(3):
            for y in range(5):
                if idx < 30:
                    porto[andar, x, y] = posicoes_iniciais[idx]
                    idx += 1

    # Preencher array balsa com posições finais (30-59 do cromossomo)
    posicoes_finais = cromossomo[30:60]
    idx = 0
    for z in range(3):
        for x in range(3):
            for y in range(4):
                if idx < len(posicoes_finais):
                    balsa[z, x, y] = posicoes_finais[idx]
                    idx += 1 

    return porto,balsa

# Teste da inicialização da população
tamanho_populacao = 10
populacao_inicial = inicializar_populacao(tamanho_populacao)

# Exibir um exemplo de cromossomo e o porto inicial
cromossomo_exemplo = populacao_inicial[0]
porto_inicial,balsa = preencher_porto_balsa(cromossomo_exemplo)

print("Cromossomo Exemplo:")
print(cromossomo_exemplo)

print("\nPorto Inicial (andar 0):")
print(porto_inicial[0])

print("\nPorto Inicial (andar 1):")
print(porto_inicial[1])

IndexError: index 2 is out of bounds for axis 2 with size 2